### ISSUE TITLE
Bug with API Routes Prefix

### ISSUE THREAD

**Issue by mrmonat** [ARCANEDEV/Localization#127]
- Localization Version: 3.0.0
- Laravel Version: 5.6.28
- PHP Version: 7.1.16

### Description:

I want to use this package inside of my routes/api.php file:
**routes/api.php**
`Route::localizedGroup(function () {
    Route::get('/test', function () {
        return 'test';
    });
});`

**Results**
Trying to access http://my-domain.com/en/api/test fails with 404 aswell as http://my-domain.com/api/en/test

**Notes**
If I remove the 'api' prefix inside the RouteServiceProviders mapApiRoutes() Method the url
http://my-domain.com/en/test works...

So I think that there is a general problem with route prefixes...

**Comment by arcanedev-maroc** [comment]
I don't recommend to use the package with your API.

Because the `api` routes doesn't have like sessions and others functionalities like `web` routes. [Check the Http Kernel](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L29-L44)

So i don't think it's going to work.

The solution is to create a custom middleware for the localization that retrieves a `lang` parameter from the url, like ` http://my-domain.com/api/test?lang=en`

You can also use the request header to specify the language

  * https://stackoverflow.com/a/13100866
  * https://medium.com/teknomuslim/multi-language-api-response-messages-in-laravel-5c9029a32e5c

**Comment by mrmonat** [comment]
Okay thank you for the response, I will use the request header to specify the locale :) 👍
