### ISSUE TITLE
How do i add an Additional Prefix in Url before locale

### ISSUE THREAD

**Issue by insp3** [ARCANEDEV/Localization#133]
Hello

Old question from mcamara days: is it possible or is there a possible in future to add prefixes before locale.

Like:
* www.example.com/en
* www.example.com/gb

* www.example.com/admin/en
* www.example.com/admin/gb

* www.example.com/b2b/en
* www.example.com/b2b/gb

and so on.

**Comment by arcanedev-maroc** [comment]
**TLDR:** Is not possible and will not add this feature.

I've choosed the **Subdirectories with gTLD** because it's **REST-compliant** structure and **easy to maintain**.

How about using this structure:

EN:
```
www.example.com/en
www.example.com/en/admin
www.example.com/en/b2b
```

GB:
```
www.example.com/gb
www.example.com/gb/admin
www.example.com/gb/b2b
```

Link: [Managing multi-regional and multilingual sites](https://support.google.com/webmasters/answer/182192?hl=en)
Related: https://github.com/mcamara/laravel-localization/issues/382
