### ISSUE TITLE
Non-static method Arcanedev\Localization\Localization::setLocale() should not be called statically

### ISSUE THREAD

**Issue by hvostuho** [ARCANEDEV/Localization#162]
- Localization Version: 8.1
- Laravel Version: 8.37
- PHP Version: 7.3.17

### Description:
**Error
Class 'Localization' not found**
Please tell me what am I doing wrong?

### Steps To Reproduce:
1. Install Laravel 8

2. Install ARCANEDEV/Localization
`composer require arcanedev/localization`

3. Then do it.
`php artisan vendor:publish --provider="Arcanedev\Localization\LocalizationServiceProvider"`

4. Add to file app/Http/routes.php
```
<?php
use Arcanedev\Localization\Localization;
use Illuminate\Support\Facades\Route;

Route::group([
    'prefix'     => Localization::setLocale(),
    'middleware' => [
        'localization-session-redirect',
        'localization-redirect',
    ],
], function() {
    Route::get('/', function() {
        return view('welcome');
    });
});
```

5. Refresh the page and see Error
**ErrorException
Non-static method Arcanedev\Localization\Localization::setLocale() should not be called statically**

**Comment by arcanedev-maroc** [comment]
You can use the `localization()` helper instead of Localization facade: `localization()->setLocale()`

Or the [Real-Time Facades](https://laravel.com/docs/8.x/facades#real-time-facades) by using this namespace `Facades\Arcanedev\Localization\Contracts\Localization` instead of `Arcanedev\Localization\Localization`
