### ISSUE TITLE
Problem with getLocales()

### ISSUE THREAD

**Issue by llioor** [ARCANEDEV/Localization#32]
I'm doing this in my locales middleware:
`Localization::setSupportedLocales(['en', 'fr']);
`
but when I'm doing this in my controller:

```
$languages = MYMODEL::getLocales();
dd($languages);
```

I'm getting this: **en,fr,es**

My model extends Model and use \Dimsav\Translatable\Translatable

Any idea why
Localization::getSupportedLocales();
is correct  but 
MYMODEL::getLocales()
is **NOT** correct?

**Comment by arcanedev-maroc** [comment]
Hi @llioor, your issue is not related to this package.

Try to check the [dimsav/laravel-translatable](https://github.com/dimsav/laravel-translatable) package and see how to change the model locales.

**Comment by llioor** [comment]
Hi, Thank you for your answer...

But only in your package I have "**set**SupportedLocales". This is one of the advantage we have in your packages isn't?  

I solve it by adding locales middleware with this code:

``` php
Localization::setSupportedLocales($user->locales);
App::make('config')->set('translatable.locales', $user->locales);
```

This code is running for every request... any other ideas?
Don't you think setSupportedLocales need to change the config as well?

**Comment by arcanedev-maroc** [comment]
Yes, this code is running for every request because you put it in a middleware.

And i don't see what you mean by changing the config file ?? 

You can use the Config Facade `Config::set('translatable.locales', $user->locales);`.
or the config helper `config()->set('translatable.locales', $user->locales);`.

**NOTE:** keep in mind that the two packages are working separately.

**Comment by llioor** [comment]
You meant "dimsav/laravel-translatable" and "ARCANEDEV/Localization" are working separately? So Yes I know and this is what creates the confusion for me.

Can you help me please:
1. If I want to set the supported locales dynamically what is the best way to do it?
Is `Localization::setSupportedLocales(['en','es','fr'])`its enough for it?
2. If I want to set the current locale to fr, is `Localization::setLocale('fr')` its enough for it?
3. I want that the dimsav/laravel-translatable package will be updated by the localization settings.
Is this enough?
`App::setLocale('fr');`
What do I need to do with the `getLocales()`? it returns the locales from the "translatable" cobfig file and not the locales from `Localization::setSupportedLocales`.
4. I want to load the supported locales and  current locale from session in the next request (will be faster).
So in the end of the middleware I will do this:

``` php
session(['supported_locales' => ['en','es','fr']]);
session(['locale' => 'fr']);
```

In the next request I will check if I have locale in my session and I will load the 3 functions from the session variables:

``` php
Localization::setSupportedLocales(session('supported_locales'));
Localization::setLocale(session('locale'));
App::setLocale(session('locale'));
```

Thank you very much in advance!

**Comment by arcanedev-maroc** [comment]
Hi @llioor,

Yes, **"dimsav/laravel-translatable"** and **"ARCANEDEV/Localization"** are working separately.
1. Yes, the `Localization::setSupportedLocales(['en','es','fr'])` is enough.
2. If you call for example the `Localization::setLocale('fr');`, it's enough to set the app locale, so you don't have to call the `App::setLocale('fr');`.
3. I can't help you with the `dimsav/laravel-translatable` package because i've never used it.
4. I can't tell you what is the best way/place to implement the load/update the supported locales and the current locale because i don't know what you want to achieve, but in my opinion, try to use the **AppServiceProvider** instead of the **Middleware** because you're not changing the localization based on your requests.

Using session or not, it depends on your needs.

Hope this helps you.

**Comment by llioor** [comment]
Thank you very much @arcanedev-maroc! perfect answer!
