### ISSUE TITLE
getSupportedLocales() should return an array instead of an object

### ISSUE THREAD

**Issue by marekstodolny** [ARCANEDEV/Localization#4]
In case somebody needs to reverse or change the order of $supportedLocales in navbar template they're forced to code a hack that extracts the array from object's protected variable.

**Comment by arcanedev-maroc** [comment]
Have you tried `$supportedLocales->toArray()` ? The `Arcanedev\Localization\Entities\LocaleCollection` object extends from `Illuminate\Support\Collection` class.

More details: http://laravel.com/docs/5.1/collections

**Comment by marekstodolny** [comment]
Yeah that explains everything :)
`toArray()` converts nested objects. `all()` doesn't so I recommend that.

Wouldn't it make sense to update the foreach loop in navbar template to use ->all(), just so new users know that $supportedLocales is a collection and not a regular array?

**Comment by arcanedev-maroc** [comment]
In my opinion, the navbar is not a big deal, i can put the two examples in the documentation or as a comment in the navbar view.

But i'm gonna wait and see if the users got the same _"issue"_ with collection instead of the regular array.

PS: i'm still working on documentation: https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#localization-entities

**Comment by arcanedev-maroc** [comment]
I'm going to close this issue because nobody is complaining about it.
