### ISSUE TITLE
User selected language

### ISSUE THREAD

**Issue by ianbarker** [ARCANEDEV/Localization#43]
I'd like to display a choice of languages when a user first visits my site and then redirect the user to their chosen language and store the choice in a cookie so that they don't get asked again on subsequent visits. However I can't work out how to do this, any help would be much appreciated.

**Comment by arcanedev-maroc** [comment]
Are you already using this package or just a new project ? 

This package offers all the features you mentioned above, just read the documentation (installation, configuration and usage sections).

Check also [these issues for answers](https://github.com/ARCANEDEV/Localization/issues?q=is%3Aissue+label%3Aquestion).
- You can start by editing [these middlewares](https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L22-L23) to `true` in your `localization` config file to store the chosen language.
- Done !

If you have more questions or encounter any issue with this package, feel free to give us more details (code sample, configs, laravel version...) to help you / solve it.

Cheers,

**Comment by ianbarker** [comment]
Hi, sorry for not replying earlier. 

I am already using the project and have the two config values set to `true`. The main problem that I have is getting the app to know if the user has selected a language or if it was automatically determined or the default is being used, this is the point at which I'd like to display the various options to the user. 

Thanks

**Comment by arcanedev-maroc** [comment]
OK, i see what you want to achieve and it's going to be a little hard to do it.

This package doesn't track the user interactions with the locales (no events or whatsoever), so you need to add your logic manually.

**1st solution:** Override/Extend the classes, you can start with [middlewares](https://github.com/ARCANEDEV/Localization/tree/master/src/Middleware), you can even create your own classes and use the Localization as an API.

**2nd solution:** Add a track logic in your localization navbar (for example) to store an additional information (DB/Session/Cookies) like `chosen_language` equals to `manual` if the user click on it otherwise return the default value => `auto`.

Feel free to make a pull request if you found a better solution :+1:

**Comment by ianbarker** [comment]
Thanks. I thought that might be the case but that it made sense to ask first. 

I'll try the events route as I like pub/sub pattern.
