### ISSUE TITLE
Localization in POST routes

### ISSUE THREAD

**Issue by devdurbs** [ARCANEDEV/Localization#81]
- Localization Version: current
- Laravel Version: 5.1
- PHP Version: 5.6 / 7.0

Thought this might be useful to others who find their post routes are responding in the default language only: 

You either need to replace form actions using 'url::' with **named** routes 'route::'
or
remember to add localization to all form actions ie. replace 

```php
Form::open(['url' => 'account/update/profile', . . .
```

with

```php
Form::open(['url' => localization()->localizeURL('account/update/profile'), . . .
```

In retrospect I suppose it's obvious but certainly took me a while to resolve!

**Comment by arcanedev-maroc** [comment]
Thanks for sharing advises with other users 👍

TBH, i'm always using **route names** because it allows you to edit your urls in one place and avoid any conflicts (i give a unique name for each route even for `GET` and `POST` routes).

I'm going to close this because it's not an issue but you can find it by clicking these labels: `docs` or `tips`.
