### ISSUE TITLE
Translated routes : No redirection with the right locale

### ISSUE THREAD

**Issue by cache-s** [ARCANEDEV/Localization#96]
Hello,

I'm having troubles with translated routes. Here is what currently works:

- mysite.dev/
- mysite.dev/en/
- mysite.dev/en/home
- mysite.dev/fr/
- mysite.dev/fr/accueil           (French for 'home')

When I don't specify the locale in the URL, this also works:

- mysite.dev/accueil => redirection => mysite.dev/fr/accueil => Nice, that's what I want

But this doesn't work:

- mysite.dev/home => not found => Not nice, I wanted a redirection to mysite.dev/en/home

Why ?
If my last URL is, for example, mysite.dev/en/home , shouldn't the locale be still set to English when I try to access it without the en/ in the URL ? I'm confused, do you have a solution ?

My web.php:
```
Route::localizedGroup(function () {
    Route::get('/', 'HomeController@index');

    Route::transGet('routes.home', function () {
        return "home";
    });

    Route::transGet('routes.about', function () {
        return "about";
    });
});
```

Regards,

**Comment by arcanedev-maroc** [comment]
Salut, 

Are you getting a `NotFoundHttpException` = 404 ?

What you want to acheive is to **duplicate** all the `localized routes` with the number of the `supported locales`, with this setup you're going to have all the possible urls translated.

This is a little bit tricky because it's outside the package scope (Illuminate\Routing\RouteCollection @ match).

Unfortunately, this is not implemented yet and it may be difficult to maintain.

Try to `dd()` the route collection to understand who it's work.

**Comment by cache-s** [comment]
Hey, thanks for your answer.

It returned a 404 NotFoundHttpException. 

By 'duplicate' you mean doing something like this ? :

```
Route::localizedGroup(function () {
    Route::get('/', 'HomeController@index');

    /*
    ** HOME PAGE ROUTES
    */
    Route::get('home', function () {
        return "home en";
    });

    Route::get('accueil', function () {
      return "home fr";
    });

    /*
    ** ABOUT PAGE ROUTES
    */
    Route::get('about', function () {
        return "about en";
    });

    Route::get('a-propos', function () {
      return "about fr";
    });
});
```

With this kind of routes I end up having things like mysite.dev/en/accueil (wrong, should be localized as fr). Should I set the locale myself and redirect ?

When I dd the route collection here is what I get :

```
array:4 [▼
  "api/user" => Route {#111 ▶}
  "/" => Route {#116 ▶}
  "accueil" => Route {#114 ▶}
  "a-propos" => Route {#112 ▶}
]
```

I'm having French routes instead of english ones. To get this, here is what I did :
- Go to => mysite.dev/en/home (works)
- Remove the localization from the url =>  mysite.dev/home (404)

It resets the language back to French ! But if the last page I visited was localized in EN, and my default language is English too, why does it reset ? Browser preferences takes over ?

**Comment by arcanedev-maroc** [comment]
By 'duplicate', i meant when you call `Route::localizedGroup()` should register all localized routes with correct `prefix` (locale).

For example:

```php
Route::localizedGroup(function () {
    Route::get('/', 'HomeController@index');

    Route::transGet('routes.home', function () {
        return "home";
    });

    Route::transGet('routes.about', function () {
        return "about";
    });
});
```

You will get 6 localized routes (without counting the api routes):

 * /en
 * /en/home
 * /en/about
 * /fr
 * /fr/accueil
 * /fr/a-propos

But it's not the case, and also you can't cache the routes for the time being.

Right now i don't have a good solution to correct the redirections.

But i didn't care about it because what it should be important (in my opinion) is the translation of the links inside of my apps => navigation.

And yes, it get the browser's preferences with this [chunk fo code](https://github.com/ARCANEDEV/Localization/blob/master/src/Utilities/LocalesManager.php#L159-L160).

You can disabled it with the config file: https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L12

**Comment by cache-s** [comment]
Hello,

Ok well, I'll stick to what I had at the beginning then. It would be a nice implementation to have by the way !

Thanks for you answers

**Comment by arcanedev-maroc** [comment]
You're welcome et bonne chance pour la suite 👍
