### ISSUE TITLE
redirect home if no translated article added

### ISSUE THREAD

**Issue by subdesign** [ARCANEDEV/Localization#98]
- Localization Version: 1.1.0
- Laravel Version: 5.4.23
- PHP Version: 7.0.19

### Description:

I have english and german articles where I use Localization, but the users do not translate all english articles to german. what is the recommended way to redirect in these cases to the german main page?

Example:
english aritcle uri:
/en/article_title/4
Language changer shows: 
/de/article_title/4 
On clicking lang changer should redirect to /de (because ID:4 article has no german translation)

thanks

**Comment by arcanedev-maroc** [comment]
You need to add a check logic in your controller to see if the translated content exists.

Otherwise, you can set a fallback content or redirect to homepage or display 404 page.

For the language changer, create your own language switcher with the available translated content.

For example: If the current article has translations, display the links for the other localizd content.

**Comment by subdesign** [comment]
thanks
